apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: toto
            - name: MYSQL_PASSWORD
              value: toto
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: pvc