apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service1
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: mysql1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30008


# kubectl apply -f -service-nodeport-web.yaml --namespace=production