apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008


# kubectl apply -f -service-nodeport-web.yaml --namespace=production