apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
    - name: mysql
      image: mysql:latest
      volumeMounts:
        - name: volume-mysql    
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eazytraing
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
volumes:
  - name: volume-mysql
    hostPath:
      path: /data-volume
      type: DirectoryOrCreate