apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvc
spec:
  containers:
    - name: mysql
      image: mysql:latest
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-data
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eazytraing
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
volumes:
  - name:  mysql-data
    persistentVolumeClaim:
      claimName: my-storage-class
